imageNum = image_index

global.price = 1000

if imageNum = 1
    global.price = 50
if imageNum = 2
    global.price = 50
if imageNum = 4
    global.price = 50
if imageNum = 5
    global.price = 50
if imageNum = 6
    global.price = 70
if imageNum = 7
    global.price = 60
if imageNum = 8
    global.price = 110
if imageNum = 9
    global.price = 50
if imageNum = 10
    global.price = 70
if imageNum = 11
    global.price = 120
if imageNum = 12
    global.price = 70
if imageNum = 13
    global.price = 130
if imageNum = 14
    global.price = 50
if imageNum = 15
    global.price = 60
if imageNum = 16
    global.price = 100
if imageNum = 17
    global.price = 70
if imageNum = 18
    global.price = 110
